produtos_de_mercado = [
    # Categoria: Mercearia / Alimentos Secos
    "Arroz Agulhinha (5kg)",
    "Feijão Carioca (1kg)",
    "Macarrão Espaguete",
    "Açúcar Refinado",
    "Sal Refinado",
    "Óleo de Soja (900ml)",
    "Café em Pó (500g)",
    "Farinha de Trigo",
    "Fermento em Pó",
    "Biscoito Maizena",
    "Leite em Pó Integral",
    "Achocolatado em Pó",
    "Atum em Lata",
    "Milho Verde em Conserva",
    "Ervilha em Conserva",
    "Molho de Tomate Tradicional",
    "Sardinha em Lata",
    "Geleia de Morango",
    "Mel (Pote)",
    "Pão de Forma Tradicional",
    "Torrada Salgada",
    "Manteiga ou Margarina (250g)",
    "Queijo Mussarela Fatiado (200g)",
    "Presunto Cozido Fatiado (200g)",
    "Ovos Brancos (Dúzia)",

    # Categoria: Bebidas
    "Água Mineral sem Gás (1.5L)",
    "Refrigerante Cola (2L)",
    "Suco de Laranja (Caixa 1L)",
    "Chá Preto em Sachê",
    "Leite Integral (Caixa 1L)",

    # Categoria: Hortifruti (Frutas e Vegetais)
    "Banana Prata (Kg)",
    "Maçã Fuji (Kg)",
    "Laranja Pêra (Kg)",
    "Limão Taiti (Kg)",
    "Tomate (Kg)",
    "Cebola (Kg)",
    "Alho (Cabeça)",
    "Batata Inglesa (Kg)",
    "Cenoura (Kg)",
    "Alface Americana (Unidade)",
    "Pimentão Verde (Unidade)",
    "Vagem (Kg)",
    "Pepino",
    "Brócolis",
    "Abacaxi",
    "Mamão Formosa",
    "Manga Palmer",
    "Aipim (Mandioca)",

    # Categoria: Carnes / Congelados
    "Peito de Frango Congelado (Kg)",
    "Carne Moída (Kg)",
    "Salsicha (Pacote)",
    "Hambúrguer Congelado",
    "Pão de Queijo Congelado (400g)",
    "Pizza Congelada",
    "Sorvete de Creme (Pote 1L)",

    # Categoria: Limpeza Doméstica
    "Detergente Líquido para Louças",
    "Sabão em Pó (1kg)",
    "Água Sanitária (1L)",
    "Desinfetante (1L)",
    "Lã de Aço (Bombril)",
    "Esponja para Louças (Pacote)",
    "Saco de Lixo (30L)",
    "Limpa Vidros",
    "Amaciante de Roupas",
    "Sabão em Barra",
    "Pano de Chão",
    "Alvejante sem Cloro",

    # Categoria: Higiene Pessoal
    "Shampoo para Cabelos Normais",
    "Condicionador",
    "Sabonete em Barra (Pacote com 4)",
    "Pasta de Dente (Tubo Grande)",
    "Escova de Dente (Média)",
    "Fio Dental",
    "Papel Higiênico (Rolo com 12)",
    "Creme Dental Infantil",
    "Lâmina de Barbear Descartável",
    "Creme de Barbear",
    "Desodorante Roll-on",
    "Absorvente Higiênico (Pacote)",
    "Algodão em Bolas",
    "Cotonetes",
    "Lenço de Papel",
    "Sabonete Líquido para Mãos",
    "Protetor Solar FPS 30",

    # Categoria: Diversos / Lanches
    "Batata Palha",
    "Ketchup (Frasco)",
    "Mostarda (Frasco)",
    "Maionese (Pote)",
    "Salgadinho de Milho (Pacote Grande)",
    "Chocolate em Barra",
    "Doce de Leite (Pote)",
    "Azeite Extra Virgem (500ml)",
    "Vinagre de Álcool",
    "Pimenta do Reino Moída",
    "Tempero Completo",
    "Gelatina em Pó",
    "Creme de Leite (Caixa)",
    "Leite Condensado (Caixa)",
    "Farinha de Mandioca"
]